development:
  adapter: postgresql
  database: meetup_resources_dev
  username:
  password:

test:
  adapter: postgresql
  database: meetup_resources_test
  username:
  password:

production:
  adapter: postgresql
  database: meetup_resources_prod
  username:
  password: